services:
  web:
    build: .
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/code/app/
      - /project/node_modules
    networks:
      - vite
    expose:
      - 5173
networks:
  vite: {}
